version: 2

jobs:
    test-python:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: python python3/emmet_test.py
            - run: |
                sudo pip install black
                black --check python3/
    test-vim:
        docker:
            - image: alpine:latest
        steps:
            - checkout
            - run: apk add make git vim neovim python3
            - run: make test-vim
            - run: make test-nvim

workflows:
    version: 2
    test-python-and-vim:
        jobs:
            - test-python
            # - test-vim
