version: 2

jobs:
    test-python-3.7:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: make test-python
            - run: |
                sudo pip install black
                black --check python3/

    test-python-3.4:
        docker:
            - image: circleci/python:3.4
        steps:
            - checkout
            - run: make test-python

    test-vim:
        docker:
            - image: alpine:latest
        steps:
            - checkout
            - run: |
                apk add make git vim neovim python3 python3-dev gcc musl-dev
                pip3 install pynvim
            - run: make test-vim
            - run: make test-nvim

workflows:
    version: 2
    test-python-and-vim:
        jobs:
            - test-python-3.7
            - test-python-3.4
            - test-vim
