version: 2

jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: python pythonx/emmet_test.py
            - run: |
                sudo pip install black
                black --check pythonx/
