version: 2

# TODO: lint with 'black'
jobs:
    build:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run:
                command: |
                    python pythonx/emmet_test.py
        branches:
            only:
                - master
                - test-circleci

