name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 1 1 *

jobs:
  vader:
    strategy:
      fail-fast: false
      matrix:
        editor: [vim, neovim]
        version: [stable, nightly]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.editor == 'neovim' }}
          configure-args: --enable-python3interp
      - run: pip install pynvim
        if: ${{ matrix.editor == 'neovim' }}
      - run: make test-${{ matrix.editor }}

  python:
    strategy:
      matrix:
        python: ['3.7', '3.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: make test-python
